### ISSUE TITLE
Async Tests display warning about missing Expected

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.analyzers#118]
This test,

```C#
[TestCase(0, 10)]
[TestCase(-100, 0)]
[TestCase(100, 200)]
[TestCase(0, 0)]
public async Task RandomAsyncTest(int low, int high)
{
    //
}
```

Shows a warning for each `TestCase`

```
2>TestAsync.cs(11,10,11,25): error NUNIT_13: Method has non-void return type, but no result is expected in ExpectedResult
```

**Comment by mikkelbu** [comment]
I don't think that this is related to #119, but due to the fact that we currently do not handle async tests very well - or at all - in the analyzers (all the issues in "Release 0.2" milestone are about async). Currently in the analyzers we have `ExpectedResult` if and only if the test method has a non-void return type, so since there is no `ExpectedResult` then we expect only `void` to be returned.

The else-branch below is executed if there is no `ExpectedResult` in the attribute, so currently we report an error if the return type is not `void`.
https://github.com/nunit/nunit.analyzers/blob/5dd6c0b258e21762cfd74ed87bc68523c872701e/src/nunit.analyzers/TestMethodUsage/TestMethodUsageAnalyzer.cs#L107-L114

**Comment by rprouse** [comment]
I can confirm that it isn't related to #119. That issue is no longer happening for me, but this one is.
