### ISSUE TITLE
Analyzers and refactorings to use string constraints instead of methods

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit.analyzers#150]
E.g. instead of 
`Assert.That("123".Contains("12"))`
should be
`Assert.That("123", Does.Contain("12"))`

Other cases:
`StartsWith` -> `Does.StartWith`
`EndsWith` -> `Does.EndWith`

**Comment by Dreamescaper** [comment]
I plan to work on that a bit later, so I can be assigned to this issue.

**Comment by mikkelbu** [comment]
I don't think that I've ever written an assertion like `Assert.That("123".Contains("12"))`, but that should not be used as argument not to implement this :)

**Comment by Dreamescaper** [comment]
Sure, because you know framework, and what constraints are available.

I'd really like to be able to enforce using constraints instead of most common boolean verifications. 
There are guys that are too lazy to read NUnit docs, even such basic once...

**Comment by mikkelbu** [comment]
> Sure, because you know framework, and what constraints are available.

Actually, most of the time I only use the most basic constraints (probably because I also don't know about most of the more advanced constrains), and currently we only use xUnit at work, so I don't get to use NUnit much besides looking into issues and PRs in the NUnit project :).

So I would write 
```csharp
var matchingElements = myList.Where(x => x.EqualTo(item));
Assert.That(matchingElements.Length, Is.EqualTo(2)); 
```
rather than
```csharp
Assert.That(myList, Has.Exactly(2).Items.EqualTo(item));
```
which gives a better failure message. 

But I very much agree with you that a failure message - like `Expected: true, Was: false` - is not very useful in most of the cases.
