### ISSUE TITLE
False error when Uri is parameter and string is argument

### ISSUE THREAD

**Issue by Denis535** [nunit/nunit.analyzers#186]
Next code leads to error, but it works.

    [TestCase( "http://www.site.com" )]
    public void Test(Uri value) {
    }

_The value of the argument at position '0' of type string cannot be assigned to the argument 'value' of type System.Uri_

**Comment by mikkelbu** [comment]
As far as I can tell this is working now (handled by `TypeConverter converter = TypeDescriptor.GetConverter(reflectionTargetType)` in `src\nunit.analyzers\Extensions\AttributeArgumentSyntaxExtensions.cs`. Which version of the analyzer are you using @Deni35?

**Comment by Deni35** [comment]
@mikkelbu, version is 0.2.0-dev-00271.

**Comment by mikkelbu** [comment]
It seems that the code behaves differently from .NET Framework and .NET Core. I first tested on 4.7.2 and it worked, but when changing the code to target .NET Core it failed with the above message. I'll have to look more into this (hopefully, in the weekend).

**Comment by Dreamescaper** [comment]
Seems like the issue is with our `GetTargetReflectionType` - it attempts to handle forwarded types in dotnet core, but handles only types from mscorelib. 
Uri type, however, is in `System` assembly in runtime (in `System.Runtime` assembly in design time), therefore `Type.GetType` returns null.

Probably special case could be added to fix this issue.
Although I'd investigate how hard would it be to remove reflection-based checks, and use static-only analysis here.

**Comment by mikkelbu** [comment]
I came to the same conclusions last weekend, but all last week as 110% booked, so did not work on this.

Even though several blogs and posts discouraged combining analyzers and reflection I still think it is needed:
* Partly, because it makes the analyzer code somewhat similar to the production code
* But more importantly, because I don't think we can capture this information - that a string can be converted to a Uri - from just static information. Currently, this is the case due to `System.UriTypeConverter`, but I cannot see us knowing this without relection (but I'm open to be wrong about this :))

I was considering alternatives:
* Trying to find the type using `Assembly.GetTypes` iterating all the assemblies (haven't tested this yet)
* Perhaps using something related to `IAssemblySymbol.ResolveForwardedType`, but that will require us to bump to Roslyn 3.0 which I want to avoid
* Try to cover as many as possible of the "normal" cases - like Double, Uri ... - using something similar to https://luisfsgoncalves.wordpress.com/2017/03/20/referencing-system-assemblies-in-roslyn-compilations/ and then just accept that we cannot cover all and don't report problems on types we cannot find
* ... (as I'm running out of battery in less than 5 minutes)

**Comment by Dreamescaper** [comment]
> I don't think we can capture this information - that a string can be converted to a Uri - from just static information

Yeah, we can describe some type mapping, which could be converted, but we definitely cannot know that e.g. `"1234"` cannot be converted to `Uri`. Which is surely valuable info, agree.
 
This concern applies to reflection approach as well - user can define custom class with custom TypeConverter, and we won't be able to handle that. Probably a rare case, of course...

> Trying to find the type using Assembly.GetTypes iterating all the assemblies (haven't tested this yet)

That would probably require to bump `netstandard` to use `AppDomain` class (which is fine).

**Comment by Dreamescaper** [comment]
I suggest the simplest fix possible for the time being - do not report diagnostic if reflection type info is not available for analyzer.
