### ISSUE TITLE
Feature request: suppress CA1001 when Dispose is called in the TearDown method

### ISSUE THREAD

**Issue by jhinder** [nunit/nunit.analyzers#568]
The .NET analyzers (from the SDK) report [CA1001](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1001) when the object under test is `IDisposable`. We're calling `Dispose` in the `[TearDown]` method, but we still have to suppress CA1001 (pragma directive, editorconfig, etc) because the .NET analyzers don't recognize the NUnit patterns and because we have `TreatWarningsAsErrors` enabled in our codebase.

Could you use the [DiagnosticSuppressor](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor?view=roslyn-dotnet-4.6.0) API to suppress CA1001 in that case?

```csharp
public sealed class C : IDisposable
{
    public void Dispose()
    {
    }
}

[TestFixture]
public class Test // CA1001: Type 'Test' owns disposable field(s) '_objectUnderTest' but is not disposable
{
    [SetUp]
    public void SetUp()
    {
        _objectUnderTest = new C();
    }

    [TearDown]
    public void TearDown()
    {
        _objectUnderTest.Dispose();
    }

    private C _objectUnderTest;
}
```

**Comment by manfred-brands** [comment]
@jhinder I know where you are coming from.

If the `TearDown` is simple, like your example, this might be doable, but as soon as there are conditional statements or indirect calls it will become virtually impossible. 
If you look at the code for the [DisposeAnalysis](https://github.com/dotnet/roslyn-analyzers/tree/main/src/Utilities/FlowAnalysis/FlowAnalysis/Analysis/DisposeAnalysis) in the Roslyn Analyzers you see what I mean.

At work we currently add the below to our .editorconfig to solve this for unit tests:
```
[*Fixture.cs]
# Types that own disposable fields should be disposable
# TODO: We agree with this rule, except for NUnit
# where fields initialized in SetUp must be disposed in TearDown.
dotnet_diagnostic.CA1001.severity = none
```

But we want to get rid of it as well because we had test not cleaning up, so it would be good to detect this.

Watch this space.

**Comment by manfred-brands** [comment]
Ok, suppression is possible.
I can get the list of offending field names. Now I have to find out of they are disposed.
