### ISSUE TITLE
Cannot load analyzer types in 3.7+

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit.analyzers#605]
Using .NET 7, upgrading the NUnit.Analyzers package from 3.6 to 3.7/3.8 leads to a sloo of build warnings for various analyzers. In the build output screenshot, note the number of warnings, almost all are from this change.

![image](https://github.com/nunit/nunit.analyzers/assets/12619902/dc94b9b3-9eb4-468f-b57c-1e563b57d6e5)

I experimented for some time looking for a minimal repro, but no luck. I'm willing to try anything out to help pinpoint the issue.

Thanks!

**Comment by manfred-brands** [comment]
Hello @RenderMichael, let's see if we can work it out 

Do you get the same errors when building from the command line using `dotnet build`?
If not, Visual Studio often requires a restart when updating analyzers 

If you still get the errors:
Can you verify that the DLL in your NuGet cache has the correct version? Maybe it got out of sync somehow which has been known to happen.
Alternatively delete the nunit.analyzers directory and rebuild your code so that it will be refetched.

What version of the .NET 7 SDK do you use?

**Comment by RenderMichael** [comment]
A simple VS restart fixed the issue. Sorry to clog the feed with this issue! It's never happened before so I assumed there was something wrong. Thanks for taking the time!
